### ISSUE TITLE
Aceitar pasta e porta como parâmetros opcionais.

### ISSUE THREAD

**Issue by gregoriokusowski** [Acad-Feevale/HTTPobre#1]
Hoje a classe ```Runner``` está com um path fixo: ```new Server("/Users/kusowski").startListening();```.

- [x] Fazer com que o server receba no construtor path e porta
- [ ] Preencher path e porta através dos parâmetros

**Comment by ehkasper** [comment]
@gregoriokusowski A classe `Server` já está recebendo o path como parâmetro e adicionei a porta.

O que tu quer dizer por "Preencher path e porta através dos parâmetros"?

**Comment by gregoriokusowski** [comment]
Parâmetros do ```main```, tipo ```args[0]``` como pasta e ```args[1]``` como porta, mas acho que podemos deixar para um segundo momento.

**Comment by ehkasper** [comment]
Okay, adicionei os dois (se eu entendi o que tu quis dizer). A única coisa que é preciso fazer agora é adicionar os argumentos quando construir o objeto. No meu caso (NetBeans) eu vou em propriedades do projeto e adiciono os dois argumentos.
