### ISSUE TITLE
Escrever resposta do server

### ISSUE THREAD

**Issue by gregoriokusowski** [Acad-Feevale/HTTPobre#2]
O método ```writeResponse``` ainda não está devidamente implementado.

- [x] Fazer a formatação e escrita do cabeçalho como String
- [x] Fazer a escrita do corpo como byte array

**Comment by ehkasper** [comment]
@gregoriokusowski Não seria melhor parsear o cabeçalho pra byte array e enviar tudo assim? Não sei se tem como enviar o cabeçalho e depois o corpo... Tem?

**Comment by ehkasper** [comment]
dá uma olhada em #4. Acho que resolve esse problema.
