### ISSUE TITLE
Implementar funcionalidades para verificar arquivos.

### ISSUE THREAD

**Issue by gregoriokusowski** [Acad-Feevale/HTTPobre#3]
A classe ```Digger``` é responsável pela busca e retorno de arquivos e respostas baseadas neles.

- [x] Implementar método ```notExists``` que fará verificará se existe arquivo ou pasta de mesmo nome
- [x] Implementar método ```isFolder``` que verificará se o determinado caminho é uma pasta

**Comment by ehkasper** [comment]
Adicionei um teste simples usando a class `File`. Por enquanto resolve o problema, para ler a pasta, vou pensar em algo e então refatorar essa parte. Mas por hora, tá funcionando
