### ISSUE TITLE
Implementar funcionalidades para geração de responses baseadas em arquivos.

### ISSUE THREAD

**Issue by gregoriokusowski** [Acad-Feevale/HTTPobre#4]
A classe ```Digger``` é responsável pela busca e retorno de arquivos e respostas baseadas neles.

- [x] Implementar método ```notFoundResponse``` que será retornado quando o arquivo solicitado não existir
- [x] Implementar método ```folderResponse``` que retornará text/html com uma listagem dos arquivos existentes dentro da pasta (com links, etc)
- [x] Implementar método ```fileResponse``` que retornará como corpo o byte array do arquivo
- [x] Implementar no método ```fileResponse``` uma maneira de responder corretamente o mime type do arquivo solicitado

**Comment by ehkasper** [comment]
Mudei algumas coisas que acho que funcionam melhor. Mas, lembrando que, pode alterar se achar que outro jeito funciona melhor.

Adicionei um método `get()` que monta a resposta a partir de Strings e retorna um `byte[]`:

```java
        public byte[] get()
        {
            String message = getHeader();
            message += "\n";
            message += getBody();
            
            return message.getBytes();
        }
```

transformei então, `byte[] body` em `String body` para facilitar esse retorno.

Com isso, implementei o `notFoundResponse` e o `fileResponse`, já lendo o arquivo e tudo mais.

@gregoriokusowski dá uma olhada e vê o que acha :)

**Comment by gregoriokusowski** [comment]
Acho que o body precisa ser ```byte[]``` mesmo, pegando por exemplo um png, se transformar pra string e depois pra ```byte[]``` ele vai se perder, não?

**Comment by ehkasper** [comment]
As respostas estão rolando. Só não sei porque o html não é interpretado no browser, acho que é algo no cabeçalho...
